version: "3.8"

services:

    # PHP Service
    php:
        build: './php_docker/'
        volumes:
            - ./src:/var/www/html

    # Apache Service
    apache:
        build: './apache_docker/'
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./www/:/var/www/html/

    # MariaDB Service
    mariadb:
        image: mariadb:10.11
        enviroment:
            MYSQL_ROOT_PASSWORD: /run/secrets/mysql_secret
        volumes:
            - mysqldata:/var/lib/mysql
        secrets:
            -mysql_secret

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb

# Volumes
volumes:
    mysqldata:

# Passwords
secrets:
    mysql_secret:
        file: ./mysql_secret.txt